# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: xyges
service: serverless-crud-motorbikes-clients

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
